from tkinter import *
from tkinter import ttk
from tkinter import messagebox
from gestorAplicacion.clasesDeAdministracion.Prestamo import Prestamo
from datetime import date
from uiMain.FieldFrame import FieldFrame
from tkcalendar import Calendar
from gestorExcepciones.erroresDeUsuario import *
from gestorExcepciones.erroresPython import * 
